<a href="https://colab.research.google.com/github/Hammad-Ahmedd/python/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import pandas as pd
import random

In [13]:
print(tf.__version__)

2.19.0


### lets create a scalar

In [14]:
scalar=tf.constant(4)
print(scalar)
print(f"Scalar dimentions {scalar.ndim}")

tf.Tensor(4, shape=(), dtype=int32)
Scalar dimentions 0


### Lets create a vector

In [15]:
vector=tf.constant([1,2,3,4,5])
print(vector)
print(f"vector dimentions {vector.ndim}")

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
vector dimentions 1


### Lets create a Matrix

In [16]:
Matrix=tf.constant([[1,2,3],[2,4,5]])
print(Matrix)
print(f"Matrix dimentions {Matrix.ndim}")

tf.Tensor(
[[1 2 3]
 [2 4 5]], shape=(2, 3), dtype=int32)
Matrix dimentions 2


### Lets create a Tensor

In [17]:
tensor=tf.constant(
    [
        [
            [1,2],
            [4,6]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)
print(tensor)
print(f"Matrix dimentions {tensor.ndim}")

tf.Tensor(
[[[1 2]
  [4 6]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Matrix dimentions 3


### What we've created so far

* <span style="color: #FF5733;"><b>Scalar:</b></span> a single number

* <span style="color: #33C1FF;"><b>Vector:</b></span> a number with direction (e.g. wind speed and direction)

* <span style="color: #28A745;"><b>Matrix:</b></span> a 2-dimensional array of numbers

* <span style="color: #9B59B6;"><b>Tensor:</b></span> an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Variable

In [18]:
# Create the same tesnor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

🔑 **Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

In [ ]:
tf.random.set_seed(42)
suffle=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tf.random.shuffle(suffle,seed=10))
print(tf.random.shuffle(suffle,seed=50))


## Other ways to make tensors

In [ ]:
print(tf.ones(5,6))
print(tf.zeros(4,3))
print(tf.range(start=0,limit=10,delta=2))

## Turn NumPy arrays into tensors

In [ ]:
import numpy as np
numpy_A =np.arange(start=0,step=10,stop=60)
numpy_A

In [ ]:
numpy_A_tensor=tf.constant(numpy_A,shape=(3,2))
numpy_A_tensor

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

In [ ]:
rank_4_tensor[:2,:3,:2,:3]

In [ ]:
# Create Rank 2 tensor
rank_2_tensor=tf.constant([[1,2],[4,5]])
# get the last item of the each row
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
once_tensor = tf.ones(shape=(2,3,2))
# You can add an outer batch axis by passing axis=0:
expend_tensor=tf.expand_dims(once_tensor,axis=0)
print(expend_tensor)
print("Tensor shape",expend_tensor.shape)
print("Tensor dimension",expend_tensor.ndim)

In [ ]:
# You can add an outer batch axis by passing axis=0:
print("When axis is 0\n",tf.expand_dims(once_tensor,axis=0))
# The new axis location matches Python list.insert(axis, 1):
print("When axis is 1\n",tf.expand_dims(once_tensor,axis=1))
# Following standard Python indexing rules, a negative axis counts from the end so axis=-1 adds an inner most dimension:
print("When axis is -1\n",tf.expand_dims(once_tensor,axis=-1))

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor+10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# We can use the tensorflow built-in function too
tf.add(tensor,10)

In [ ]:
# Original tensor is unchanged
tensor

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
tf.matmul(tensor,tensor)

In [ ]:
# Matrix mutliplication with Python operator "@"
tensor @ tensor

In [ ]:
tensor.shape

In [ ]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

In [ ]:
# Try to matrix multiply tensors of same shape
tf.matmul(X, Y)

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

In [ ]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

In [ ]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

In [20]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

NameError: name 'X' is not defined

📖 **Resource:** Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**The dot product**

Matrix multiplication is also referrred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
# Perform matrix mutliplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n") # "\n" is for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will tranpose (rather than reshape) one of the tensors to get satisify the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
tf.__version__


In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

In [ ]:
D=tf.cast(B,dtype=tf.float16)

D , D.dtype

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
tensor_range=tf.range(start=2,limit=10,delta=1)
tensor_aggregation=tf.constant(tensor_range,shape=(2,4))
tensor_aggregation

In [ ]:
tf.reduce_max(tensor_aggregation)

In [ ]:
tf.reduce_min(tensor_aggregation)

In [ ]:
tf.reduce_min(tensor_aggregation,axis=0)

In [ ]:
tf.reduce_min(tensor_aggregation,axis=1)

In [ ]:
tensor_mean=tf.reduce_mean(tensor_aggregation)
tensor_mean

In [ ]:
tf.reduce_mean(tensor_aggregation[:,:3],axis=0)

In [ ]:
tf.reduce_mean(tensor_aggregation,axis=0,keepdims=False)

In [ ]:
tf.reduce_mean(tensor_aggregation,axis=0,keepdims=True)

In [ ]:
tensor_aggregation_sum=tf.math.reduce_sum(tensor_aggregation,axis=0,keepdims=True)
tensor_aggregation_sum.numpy(),tensor_aggregation_sum.ndim

In [ ]:
small_tensor=tf.constant([[1,2,3,6]],dtype=tf.float16)
tf.math.reduce_variance(small_tensor,axis=1)

In [ ]:
tf.math.reduce_std(small_tensor)