## NumPy Array Operations

In [2]:
import numpy as np

In [1]:
# Simple List
arr_1d=[1,2,3,4,5,6,7,8,9,10]
print("Basic Slice:",arr_1d[1:9])
print("Array skip step:",arr_1d[1:11:2])
print("Negative number:",arr_1d[-1])

Basic Slice: [2, 3, 4, 5, 6, 7, 8, 9]
Array skip step: [2, 4, 6, 8, 10]
Negative number: 10


In [ ]:
# Numpy Array
arr_2d=np.array([
    [1,2,4],
    [4,5,6],
    [7,8,9]
])

print("Specific Index:",arr_2d[2,1])
print("Entire Row:",arr_2d[1])
print("Entire Coloum:",arr_2d[:,0])

Specific Index: 8
Entire Row: [4 5 6]
Entire Coloum: [1 4 7]


## Sorting

In [59]:
unshortedarr=np.array([2,3,4,1])
print("Shorted array:",np.sort(unshortedarr))

arr_2d_unshorted=np.array([
    [7,5],
    [3,4],
    [6,9]
])

print("2s array:",np.sort(arr_2d_unshorted,axis=0))

Shorted array: [1 2 3 4]
2s array: [[3 4]
 [6 5]
 [7 9]]


## Filtering

In [30]:
arr_filter=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_filter[arr_filter % 2==0])

[ 2  4  6  8 10]


## Filter With Mask

In [ ]:
num=np.array([1,2,3,4,5,6,7])
mask=num>2
print(num[mask])

[False False  True  True  True  True  True]
[3 4 5 6 7]


## Fancy indexing vs np.Where()

In [10]:
indician=[0,2,9]
num_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(num_array[indician])
where_result=np.where(num_array>5)
print(num_array[where_result])

[ 1  3 10]
[ 6  7  8  9 10]


In [29]:
# 1️⃣ Create an array
arr_where_result = np.array([5, 12, 7, 18, 3])

# 2️⃣ Use np.where to label values greater than 10 as "Big" and others as "Small"
where_g = np.where(arr_where_result > 10, "Big", "Small")
print("Label based on condition (>10):")
print(where_g)
# Output: ['Small' 'Big' 'Small' 'Big' 'Small']


# 3️⃣ Use nested np.where to assign numeric categories:
# If value < 10 → 0
# If value <= 20 → 1
# Else (>20) → 2
where_np = np.where(arr_where_result < 10, 0,
             np.where(arr_where_result <= 20, 1, 2))
print("\nNumeric categories based on range:")
print(where_np)
# Output: [0 1 0 1 0]


# 4️⃣ Create a 2D array
arr_w = np.array([
    [12, 8, 5],
    [20, 25, 7],
    [3, 15, 18]
])

# 5️⃣ Replace all values greater than 10 with their double,
# otherwise replace with 0
where_arr = np.where(arr_w > 10, arr_w * 2, 0)
print("\nDouble values >10, else 0:")
print(where_arr)
# Output:
# [[24  0  0]
#  [40 50  0]
#  [ 0 30 36]]


Label based on condition (>10):
['Small' 'Big' 'Small' 'Big' 'Small']

Numeric categories based on range:
[0 1 0 1 0]

Double values >10, else 0:
[[24  0  0]
 [40 50  0]
 [ 0 30 36]]


## Adding And Removig Array

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 4 5 6 7 8]


In [34]:
a=np.array([[1,2,4],
            [2,9,8]])
b=np.array([[3,6,4],
            [4,6,8]])
c=np.array([[6,4,4],
            [7,5,8]])

print(a.shape==b.shape)

True


In [47]:
arr_simple_2d=np.array([
    [1,2,3],
    [4,5,6]
    ])

arr_vStack=np.array([7,8,9])
print(np.vstack((arr_simple_2d,arr_vStack)))

arr_hStack=np.array([[1,2],[4,4]])
print(np.hstack((arr_simple_2d,arr_hStack)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 1 2]
 [4 5 6 4 4]]


In [55]:
arrdelete=np.array([1,3,5,6,7])
delete=np.delete(arrdelete,4)
print("Array After Delete: ",delete)

Array After Delete:  [1 3 5 6]


In [57]:
arr_new = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Delete row with index 1 (the second row)
new_arr = np.delete(arr_new, 1, axis=0)
print(new_arr)

[[1 2 3]
 [7 8 9]]


In [166]:
array_main=np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
print(array_main[:, :3])
print(np.sum(array_main[:, :3], axis=1))

[[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]
 [130 140 150]]
[ 60 180 300 420]


## Random Module

In [ ]:
randomarr=np.random.randint(3,100,(2,3))
print(randomarr)

random_choice=np.array([1,2,3,4,5])
print(np.random.choice(random_choice,3,))



[[92 81  8]
 [87 80 35]]
[2 3 2]


## np.split() np.array_split()

In [ ]:
split_arr=np.array([
    [1,2,3,],
    [1,2,3,],
    [1,2,3,],
    [5,6,7]
    ])
# ⚠ Important: The array must be divisible evenly. If not, it gives an error.
print(np.split(split_arr,2,axis=0))
# Meaning: Similar to np.split(), but doesn’t require equal parts.
print(np.array_split(split_arr,2,axis=1))

[array([[1, 2, 3],
       [1, 2, 3]]), array([[1, 2, 3],
       [5, 6, 7]])]
[array([[1, 2],
       [1, 2],
       [1, 2],
       [5, 6]]), array([[3],
       [3],
       [3],
       [7]])]
