In [45]:
import numpy as np

## 1️⃣ Creating Arrays

In [46]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


### Common Array Creation

In [47]:
print(f"Zeros {np.zeros(3)}")
print(f"Ones {np.ones(5)}")
print(f"Arange {np.arange(0, 10, 2)}")
print(f"linspace {np.linspace(0, 1, 5)}")

Zeros [0. 0. 0.]
Ones [1. 1. 1. 1. 1.]
Arange [0 2 4 6 8]
linspace [0.   0.25 0.5  0.75 1.  ]


## 2️⃣ Array Shape & Reshaping

In [48]:
a = np.array([1,2,3,4])
b = a.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


### Important attributes:

In [49]:
arr=np.array([[1,2,3],[4,5,6]])
print(f"Shape: {arr.shape}")
print(f"Number of dimensions: {arr.ndim}")
print(f"Total elements: {arr.size}")
print(f"Data type: {arr.dtype}")

Shape: (2, 3)
Number of dimensions: 2
Total elements: 6
Data type: int64


## 3️⃣ Indexing & Slicing

In [50]:
a = np.array([10,20,30,40])
print(a[1])
print(a[1:3])

20
[20 30]


## 4️⃣ Mathematical Operations

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * 2)
print(a.mean())
print(a.sum())

[5 7 9]
[2 4 6]
2.0
6


## 5️⃣ Broadcasting (Very Important 🔥)

In [52]:
a = np.array([1,2,3])
print(a + 5)

[6 7 8]


## 6️⃣ Random Numbers

In [53]:
np.random.rand(3)
np.random.randint(1,10,5)

array([2, 4, 4, 8, 7], dtype=int32)

## 7️⃣ Boolean Masking (Important for ML)

In [54]:
a = np.array([10,20,30,40])
print(a[a > 20])

[30 40]


## 8️⃣ Matrix Multiplication

In [55]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


## 9️⃣ Linear Algebra (For ML)

In [56]:
np.linalg.det(a)
np.linalg.inv(a)
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))