In [155]:
import tensorflow as tf
import pandas as pd
import random

In [156]:
print(tf.__version__)

2.21.0


### lets create a scalar

In [157]:
scalar=tf.constant(4)
print(scalar)
print(f"Scalar dimentions {scalar.ndim}")

tf.Tensor(4, shape=(), dtype=int32)
Scalar dimentions 0


### Lets create a vector

In [158]:
vector=tf.constant([1,2,3,4,5])
print(vector)
print(f"vector dimentions {vector.ndim}")

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
vector dimentions 1


### Lets create a Matrix

In [159]:
Matrix=tf.constant([[1,2,3],[2,4,5]])
print(Matrix)
print(f"Matrix dimentions {Matrix.ndim}")

tf.Tensor(
[[1 2 3]
 [2 4 5]], shape=(2, 3), dtype=int32)
Matrix dimentions 2


### Lets create a Tensor

In [160]:
tensor=tf.constant(
    [
        [
            [1,2],
            [4,6]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)
print(tensor)
print(f"Matrix dimentions {tensor.ndim}")

tf.Tensor(
[[[1 2]
  [4 6]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Matrix dimentions 3


### What we've created so far

* <span style="color: #FF5733;"><b>Scalar:</b></span> a single number

* <span style="color: #33C1FF;"><b>Vector:</b></span> a number with direction (e.g. wind speed and direction)

* <span style="color: #28A745;"><b>Matrix:</b></span> a 2-dimensional array of numbers

* <span style="color: #9B59B6;"><b>Tensor:</b></span> an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Variable 

In [161]:
# Create the same tesnor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [162]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 **Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.set_seed(42)
suffle=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tf.random.shuffle(suffle,seed=10))
print(tf.random.shuffle(suffle,seed=50))


tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[4 5 6]
 [7 8 9]
 [1 2 3]], shape=(3, 3), dtype=int32)


## Other ways to make tensors

In [ ]:
print(tf.ones(5,6))
print(tf.zeros(4,3))
print(tf.range(start=0,limit=10,delta=2))

tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int8)
tf.Tensor([0 0 0 0], shape=(4,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


## Turn NumPy arrays into tensors

In [ ]:
import numpy as np
numpy_A =np.arange(start=0,step=10,stop=60)
numpy_A

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
numpy_A_tensor=tf.constant(numpy_A,shape=(3,2))
numpy_A_tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 0, 10],
       [20, 30],
       [40, 50]])>

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


In [ ]:
rank_4_tensor[:2,:3,:2,:3]

<tf.Tensor: shape=(2, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create Rank 2 tensor
rank_2_tensor=tf.constant([[1,2],[4,5]])
# get the last item of the each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
once_tensor = tf.ones(shape=(2,3,2))
# You can add an outer batch axis by passing axis=0:
expend_tensor=tf.expand_dims(once_tensor,axis=0)
print(expend_tensor)
print("Tensor shape",expend_tensor.shape)
print("Tensor dimension",expend_tensor.ndim)

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(1, 2, 3, 2), dtype=float32)
Tensor shape (1, 2, 3, 2)
Tensor dimension 4


In [ ]:
# You can add an outer batch axis by passing axis=0:
print("When axis is 0\n",tf.expand_dims(once_tensor,axis=0))
# The new axis location matches Python list.insert(axis, 1):
print("When axis is 1\n",tf.expand_dims(once_tensor,axis=1))
# Following standard Python indexing rules, a negative axis counts from the end so axis=-1 adds an inner most dimension:
print("When axis is -1\n",tf.expand_dims(once_tensor,axis=-1))

When axis is 0
 tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(1, 2, 3, 2), dtype=float32)
When axis is 1
 tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(2, 1, 3, 2), dtype=float32)
When axis is -1
 tf.Tensor(
[[[[1.]
   [1.]]

  [[1.]
   [1.]]

  [[1.]
   [1.]]]


 [[[1.]
   [1.]]

  [[1.]
   [1.]]

  [[1.]
   [1.]]]], shape=(2, 3, 2, 1), dtype=float32)


### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [163]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [164]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [165]:
# We can use the tensorflow built-in function too
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [166]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them: 

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [167]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [169]:
# Matrix mutliplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>