In [23]:
import tensorflow as tf
import pandas as pd

In [24]:
print(tf.__version__)

2.21.0


### lets create a scalar

In [25]:
scalar=tf.constant(4)
print(scalar)
print(f"Scalar dimentions {scalar.ndim}")

tf.Tensor(4, shape=(), dtype=int32)
Scalar dimentions 0


### Lets create a vector

In [26]:
vector=tf.constant([1,2,3,4,5])
print(vector)
print(f"vector dimentions {vector.ndim}")

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
vector dimentions 1


### Lets create a Matrix

In [27]:
Matrix=tf.constant([[1,2,3],[2,4,5]])
print(Matrix)
print(f"Matrix dimentions {Matrix.ndim}")

tf.Tensor(
[[1 2 3]
 [2 4 5]], shape=(2, 3), dtype=int32)
Matrix dimentions 2


### Lets create a Tensor

In [28]:
tensor=tf.constant(
    [
        [
            [1,2],
            [4,6]
        ],
        [
            [5,6],
            [7,8]
        ]
    ]
)
print(tensor)
print(f"Matrix dimentions {tensor.ndim}")

tf.Tensor(
[[[1 2]
  [4 6]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Matrix dimentions 3


### What we've created so far

* <span style="color: #FF5733;"><b>Scalar:</b></span> a single number

* <span style="color: #33C1FF;"><b>Vector:</b></span> a number with direction (e.g. wind speed and direction)

* <span style="color: #28A745;"><b>Matrix:</b></span> a 2-dimensional array of numbers

* <span style="color: #9B59B6;"><b>Tensor:</b></span> an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Variable 

In [29]:
# Create the same tesnor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [30]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 **Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
random=tf.random.uniform(shape=(),minval=1,maxval=12,seed=10)
random

<tf.Tensor: shape=(), dtype=float32, numpy=9.62955093383789>