# NUMPY

In [3]:
import numpy as np

## Creating numpy array from the list

In [5]:
arr_1D=np.array([1,2,3])
print("1D Array",arr_1D)

arr_2D=np.array([[1,2,3],[4,5,6]])
print("2D Array", arr_2D)

1D Array [1 2 3]
2D Array [[1 2 3]
 [4 5 6]]


# list Vs numpy array

In [ ]:
list_1=[1,2,3,4,5]
print(list_1*2)

numpy_arr=np.array([1,2,3,4,5])
print(numpy_arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


## Creating Arrays From Scratch

In [ ]:
ones=np.ones((3,4))
print("Ones Arry:\n", ones)

zeros=np.zeros((1,5))
print("zeros Arry:\n", zeros)

full=np.full((2,4),5)
print("full Arry:\n", full)

random=np.random.random((3,6))
print("random Arry:\n",random)

sequence=np.arange(0,11,3)
print("sequence Arry:\n", sequence)

Ones Arry:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
zeros Arry:
 [[0. 0. 0. 0. 0.]]
full Arry:
 [[5 5 5 5]
 [5 5 5 5]]
random Arry:
 [[0.4625837  0.65007263 0.11777572 0.92082994 0.93146906 0.92768764]
 [0.60212322 0.85320561 0.97287051 0.40615986 0.83937105 0.12578872]
 [0.40062889 0.91503477 0.16137456 0.94747338 0.42330757 0.51609372]]
sequence Arry:
 [0 3 6 9]


## Vector , Matrix , Tensor

In [25]:
vector=np.array([1,2,3,4,5])
print("Vector: \n",vector)

matrix=np.array([
    [1,2,3],
    [3,4,5]
])
print("matrix: \n",matrix)

tensor=np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[9,10,11,12],[12,13,15,16]]
])
print("tensor: \n",tensor)


Vector: 
 [1 2 3 4 5]
matrix: 
 [[1 2 3]
 [3 4 5]]
tensor: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 15 16]]]
