## Advance operation on business examples

In [65]:
import numpy as np
import matplotlib.pyplot as plt

In [46]:
# Data structure: [restaurant_id, 2022, 2023, 2024, 2025]
sales_data = np.array([
[1, 150000, 180000, 220000, 250000],# Paradise Biryani
[2, 120000, 140000, 160000, 190000],# Beijing Bites
[3, 200000, 230000, 260000, 300000],# Pizza Hub
[4, 180000, 210000, 240000, 270000],# Burger Point
[5, 160000, 185000, 205000, 230000]#Chai Point
])
print("Sales data Shape: ",sales_data.shape)

Sales data Shape:  (5, 5)


In [64]:
print("First Three Restaurant: \n",sales_data[:3])
print("Sum Of All Restaurent data:",np.sum(sales_data[:,1:]))

# Min Sales per restaurent
print("Min Sales per restaurent: ",np.min(sales_data[:,1:],axis=1))

# Mix sales per year
print("Mix sales per year",np.max(sales_data[:,1:],axis=0))

# Average Sales per restaurent
print("Average: ",np.average(sales_data[:,1:],axis=1))

First Three Restaurant: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Sum Of All Restaurent data: 4080000
Min Sales per restaurent:  [150000 120000 200000 180000 160000]
Mix sales per year [200000 230000 260000 300000]
Average:  [200000. 152500. 247500. 225000. 195000.]
